const env = process.env

export default {
	SESSION_KEY: [ env.SESSION_KEY ],
	PASSWORD_HASH: env.PASSWORD_HASH,
	SENTRY: env.SENTRY,
	MONGO_URI: env.MONGO_URI,
	PORT: env.PORT,
	FANPAGE_TOKEN: env.FANPAGE_TOKEN,
	FE_VERSION: env.FE_VERSION,
	AIRTABLE_KEY: env.AIRTABLE_KEY,
    MASOFFER_AIRTALBE_BASE: env.MASOFFER_AIRTALBE_BASE
}
